# Generated by Django 3.2.20 on 2023-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230724_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='login_reqire',
            field=models.BooleanField(default=False),
        ),
    ]
