# Generated by Django 3.2.20 on 2023-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230726_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='login_reqire',
        ),
        migrations.AddField(
            model_name='post',
            name='login_reqire',
            field=models.BooleanField(default=False),
        ),
    ]
