# Generated by Django 3.2.20 on 2023-07-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230726_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='login_reqire',
            new_name='login_require',
        ),
    ]
